// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG59lDIFmGzulL2Quypij8kOUQu6cFZ0c',
    appId: '1:310724449970:web:a004937724c467ecea1bab',
    messagingSenderId: '310724449970',
    projectId: 'carforce-bdk6969',
    authDomain: 'carforce-bdk6969.firebaseapp.com',
    storageBucket: 'carforce-bdk6969.appspot.com',
    measurementId: 'G-JP14M0Z01J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6LnYQu_Inm4CTUMuZPPqcKU9sswcN4ww',
    appId: '1:310724449970:android:d23de411d40c6a73ea1bab',
    messagingSenderId: '310724449970',
    projectId: 'carforce-bdk6969',
    storageBucket: 'carforce-bdk6969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9_dkfUmyrb6PFonij9VOdyPyiLT-TX3I',
    appId: '1:310724449970:ios:54d9b223d5725165ea1bab',
    messagingSenderId: '310724449970',
    projectId: 'carforce-bdk6969',
    storageBucket: 'carforce-bdk6969.appspot.com',
    iosBundleId: 'com.example.carforce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9_dkfUmyrb6PFonij9VOdyPyiLT-TX3I',
    appId: '1:310724449970:ios:24f3886828428a98ea1bab',
    messagingSenderId: '310724449970',
    projectId: 'carforce-bdk6969',
    storageBucket: 'carforce-bdk6969.appspot.com',
    iosBundleId: 'com.example.carforce.RunnerTests',
  );
}
